version: 2
updates:
  - package-ecosystem: maven
    directory: "/cnf"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop

  - package-ecosystem: npm
    directory: "/ui"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    groups:
      capacitor:
        patterns:
          - "@capacitor/*"
      eslint:
        patterns:
          - "@angular-eslint/*"
          - "@stylistic/eslint-plugin"
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: develop
