# Drone-CI
# 
# Um den Docker Container fuer build ('openems-build') zu aktualisieren:
# - ssh auf gitvm
# - cd /root/fems/tools
# - git pull
# - bash drone-docker.sh

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.gradle
      - /drone/.npm
    volumes:
      - cache:/cache

  build-ui:
    image: node:16
    commands:
      - cd ui
      - npm ci --prefer-offline --cache /drone/.npm
      - sed --in-place s#/m/#/${DRONE_BRANCH}/#g angular.json
      - node_modules/.bin/ng build -c "fenecon,fenecon-backend-prod,prod"
      - node_modules/.bin/ng lint

  ui-unit-test:
    image: node:16
    commands:
      - cd ui
      - npm ci
      - apt-get update
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt install -y ./google-chrome*.deb;
      - export CHROME_BIN=/usr/bin/google-chrome
      - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      #- node_modules/.bin/ng test app --watch false --code-coverage

  build-java:
    when:
      branch: 
        exclude:
          - ui_dev/*
          - feature/ui-*
    image: openems-build:latest
    environment:
      - GRADLE_USER_HOME=/drone/.gradle
    commands:
      - sed --in-place 's#\(VERSION_STRING = .*\)";#\1-'"${DRONE_BRANCH}"'";#g' io.openems.common/src/io/openems/common/OpenemsConstants.java
      - ./gradlew build buildEdge
      - ./gradlew resolve.BackendApp
      - git diff --exit-code io.openems.backend.application/BackendApp.bndrun
      - ./gradlew resolve.EdgeApp
      - git diff --exit-code io.openems.edge.application/EdgeApp.bndrun
      - cp build/openems.jar ui/target

  refresh-dev:
    image: appleboy/drone-scp
    host: 10.0.0.40
    user: fenecon-docs
    secrets: 
      - source: ssh_key_intranet 
        target: scp_key
    rm: true
    source: ./ui/target
    strip_components: 3
    target: /opt/gitea/data/openems-ui-dev/html/${DRONE_COMMIT_BRANCH}

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/.gradle
      - /drone/.npm
    volumes:
      - cache:/cache
