image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./gradlew build -x test
  - init: cd ui && npm install
  - command: cd ui && ng serve --host 0.0.0.0 --disable-host-check

ports:
  - port: 4200
    onOpen: open-browser