image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./gradlew build buildEdge -x test
    command: java -jar build/openems-edge.jar
  - init: cd ui && npm install
    command: ng serve --host 0.0.0.0 --disable-host-check

ports:
  - port: 8080
    onOpen: ignore
  - port: 8084
    onOpen: ignore
  - port: 8085
    onOpen: ignore
  - port: 4200
    onOpen: open-browser