image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./gradlew build buildEdge -x test
    command: java 
      -Dfelix.cm.dir=$(pwd)/tools/docker/openems-edge/config.d
      -Dopenems.data.dir=$(pwd)/tools/docker/openems-edge/data
      -jar build/openems-edge.jar
  - init: cd ui && npm install
    command: ng serve 
      -c gitpod
      --host 0.0.0.0
      --disable-host-check

ports:
  - port: 8080
    onOpen: ignore
  - port: 8084
    onOpen: ignore
  - port: 8085
    onOpen: ignore
  - port: 4200
    onOpen: open-browser