sudo: false

language: java
jdk:
  - openjdk8
services:
  - docker

install: ./gradlew --version

script: ./gradlew antora aggregatedJavadocs --continue --info
#script: ./gradlew antora --continue --info

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
  repo: sfeilmeier/openems.io
  target-branch: master
  local-dir: build/site
