sudo: false

language: java
jdk:
  - openjdk8
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - libstdc++-4.9-dev

install: ./gradlew --version

#script: ./gradlew antora aggregatedJavadocs --continue --stacktrace
script: ./gradlew antora --continue --stacktrace

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
  repo: sfeilmeier/openems.io
  target-branch: master
  local-dir: build/site