sudo: false

matrix:
  include:
    - language: java
      jdk:
       - openjdk8
      script:
       - ./gradlew build
       - ./gradlew resolve.BackendApp
       - git diff --exit-code io.openems.backend.application/BackendApp.bndrun
       - ./gradlew resolve.EdgeApp
       - git diff --exit-code io.openems.edge.application/EdgeApp.bndrun
       - ./gradlew buildAggregatedJavadocs --continue
       - ./gradlew buildAntoraDocs --continue
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: develop
        repo: OpenEMS/openems.io
        target-branch: master
        local-dir: build/www

    - language: node_js
      node_js: lts/*
      script:
       - ./gradlew buildUiForEdge --continue

