sudo: false

language: java

jdk:
  - openjdk8

install: ./gradlew --version

script: ./gradlew javadoc --continue

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
  repo: sfeilmeier/openems.io
  target-branch: master
  local-dir: io.openems.common/generated/docs/javadoc