sudo: false

language: java

jdk:
  - openjdk8
node_js:
  - 10

install: ./gradlew --version

script:
  - ./gradlew build -x test
  - ./gradlew buildUiForEdge --continue
  - ./gradlew buildAggregatedJavadocs --continue
  - ./gradlew buildAntoraDocs --continue

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
  repo: OpenEMS/openems.io
  target-branch: master
  local-dir: build/www
