# Woodpecker-CI
# 
# Um den Docker Container fuer build ('openems-build') zu aktualisieren:
# - ssh auf gitvm
# - cd /root/fems/tools
# - git pull
# - bash drone-docker.sh

clone:
  git-clone:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'io.openems*/**', '**/*gradle*', '.woodpecker/.java-build.yml' ]
    image: woodpeckerci/plugin-git:v1.6.1
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: false
      partial: true

pipeline:
  restore-cache:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'io.openems*/**', '**/*gradle*', '.woodpecker/.java-build.yml' ]
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /woodpecker/.gradle
      - /woodpecker/.m2
    volumes:
      - cache:/cache

  build-java:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'io.openems*/**', '**/*gradle*', '.woodpecker/.java-build.yml' ]
    image: openems-build:latest
    environment:
      - GRADLE_USER_HOME=/woodpecker/.gradle
    commands:
      - mkdir -p /woodpecker/.m2 && ln -s /woodpecker/.m2 ~/.m2
      - ./gradlew build
      - ./gradlew resolve.EdgeApp
      - ./gradlew resolve.BackendApp
      - git diff --exit-code io.openems.edge.application/EdgeApp.bndrun io.openems.backend.application/BackendApp.bndrun

  rebuild-cache:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'io.openems*/**', '**/*gradle*', '.woodpecker/.java-build.yml' ]
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /woodpecker/.gradle
      - /woodpecker/.m2
    volumes:
      - cache:/cache