# Woodpecker-CI
# 
# Um den Docker Container fuer build ('openems-build') zu aktualisieren:
# - ssh auf gitvm
# - cd /root/fems/tools
# - git pull
# - bash drone-docker.sh

variables:
  - &sftp-settings
    server: 10.0.0.40
    username: user
    password: pass
    ignore_branch: true
    port: 2222
    path: /cache
    mount:
      - cache

clone:
  git:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: woodpeckerci/plugin-git

steps:
  restore-cache:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: appleboy/drone-sftp-cache
    settings:
      restore: true
      <<: *sftp-settings
    group: restore

  build-ui:
    when:
      branch:
        exclude: [main, develop, '**/heckert/**']
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: openems-build:latest
    commands:
      - export CACHE=$CI_WORKSPACE/cache
      - mkdir -p $CACHE
      - export npm_config_cache=$CACHE/npm
      - export NG_CLI_CACHE_PATH=$CACHE/angular-cli
      - export NODE_MODULES_CACHE=$CACHE/node_modules # TODO
      - cd ui
      - npm ci --prefer-offline --cache $CACHE/npm
      - sed --in-place s#/m/#/${CI_COMMIT_BRANCH}/#g angular.json
      - node_modules/.bin/ng config cli.cache.path "$NG_CLI_CACHE_PATH"
      - node_modules/.bin/ng build -c "fenecon,fenecon-backend-prod,prod"
      - node_modules/.bin/ng lint
      - export CHROME_BIN=/usr/bin/google-chrome-stable
      - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    group: build
  
  # remove after woodpecker update
  build-ui-heckert:
    when:
      branch:
        include: [ '**/heckert/**' ]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: openems-build:latest
    commands:
      - export CACHE=$CI_WORKSPACE/cache
      - mkdir -p $CACHE
      - export npm_config_cache=$CACHE/npm
      - export NG_CLI_CACHE_PATH=$CACHE/angular-cli
      - export NODE_MODULES_CACHE=$CACHE/node_modules # TODO
      - cd ui
      - npm ci --prefer-offline --cache $CACHE/npm --force
      - sed --in-place s#/m/#/${CI_COMMIT_BRANCH}/#g angular.json
      - node_modules/.bin/ng config cli.cache.path "$NG_CLI_CACHE_PATH"
      - node_modules/.bin/ng build --base-href /${CI_COMMIT_BRANCH}/ --deploy-url /${CI_COMMIT_BRANCH}/ -c "heckert,heckert-backend-prod,prod"
      - node_modules/.bin/ng lint
      - export CHROME_BIN=/usr/bin/google-chrome-stable
      - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    group: build

  rebuild-cache:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: appleboy/drone-sftp-cache
    settings:
      rebuild: true
      <<: *sftp-settings
    group: refresh

  refresh-dev:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: appleboy/drone-scp:latest
    settings:
      host: 10.0.0.40
      user: fenecon-docs
      key:
        from_secret: ssh_key_intranet
      #rm: true
      source: ./ui/target
      strip_components: 3
      target: /opt/gitea/data/openems-ui-dev/html/${CI_COMMIT_BRANCH}
    group: refresh

  refresh-location:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: appleboy/drone-ssh:latest
    settings:
      host: 10.0.0.40
      username: fenecon-docs
      timeout: 10s
      key: 
        from_secret: ssh_key_intranet 
      script:
        - /opt/gitea/data/openems-ui-dev/refresh-location.sh ${CI_COMMIT_BRANCH}
    group: refresh