# Woodpecker-CI
# 
# Um den Docker Container fuer build ('openems-build') zu aktualisieren:
# - ssh auf gitvm
# - cd /root/fems/tools
# - git pull
# - bash drone-docker.sh

clone:
  git-clone:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: woodpeckerci/plugin-git:v1.6.1
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: false
      partial: true

pipeline:
  restore-cache:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /woodpecker/.npm
      - /woodpecker/.ng
    volumes:
      - cache:/cache
    group: restore

  build-ui:
    when:
      branch:
        exclude: [main, develop, '**/heckert/**']
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: openems-build:latest
    commands:
      - cd ui
      - npm ci --prefer-offline --cache /woodpecker/.npm --force
      - sed --in-place s#/m/#/${CI_COMMIT_BRANCH}/#g angular.json
      - node_modules/.bin/ng config cli.cache.path "/woodpecker/.ng"
      - node_modules/.bin/ng build --base-href /${CI_COMMIT_BRANCH}/ --deploy-url /${CI_COMMIT_BRANCH}/ -c "fenecon,fenecon-backend-prod,prod"
      - node_modules/.bin/ng lint
      - export CHROME_BIN=/usr/bin/google-chrome-stable
      - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    group: build
  
  # remove after woodpecker update
  build-ui-heckert:
    when:
      branch:
        include: [ '**/heckert/**' ]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: openems-build:latest
    commands:
      - cd ui
      - npm ci --prefer-offline --cache /woodpecker/.npm --force
      - sed --in-place s#/m/#/${CI_COMMIT_BRANCH}/#g angular.json
      - node_modules/.bin/ng config cli.cache.path "/woodpecker/.ng"
      - node_modules/.bin/ng build --base-href /${CI_COMMIT_BRANCH}/ --deploy-url /${CI_COMMIT_BRANCH}/ -c "heckert,heckert-backend-prod,prod"
      - node_modules/.bin/ng lint
      - export CHROME_BIN=/usr/bin/google-chrome-stable
      - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    group: build
    
  refresh-dev:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: appleboy/drone-scp
    host: 10.0.0.40
    user: fenecon-docs
    secrets:
      - source: ssh_key_intranet
        target: ssh_key
    rm: true
    source: ./ui/target
    strip_components: 3
    target: /opt/gitea/data/openems-ui-dev/html/${CI_COMMIT_BRANCH}
    group: refresh

  refresh-location:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: appleboy/drone-ssh
    host: 10.0.0.40
    username: fenecon-docs
    timeout: 10s
    key:
      from_secret: ssh_key_intranet
    script:
      - /opt/gitea/data/openems-ui-dev/refresh-location.sh ${CI_COMMIT_BRANCH}
    group: refresh

  rebuild-cache:
    when:
      branch:
        exclude: [main, develop]
      path:
        include: [ 'ui/**', '.woodpecker/.ui-build.yml' ]
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /woodpecker/.npm
      - /woodpecker/.ng
    volumes:
      - cache:/cache
    group: refresh