variables:
  - &sftp-settings
    server: ${CACHE_SERVER}
    username: user
    password: pass
    ignore_branch: true
    port: 2222
    path: /cache
    mount:
      - cache

  - &rsync-settings
    user: fenecon-docs
    hosts: 
      - ${ARTIFACT_SERVER}
    port: 22
    key:
      from_secret: ssh_key_intranet

  - &main-build
    branch: [main, develop]

  - &message-debian
    evaluate: 'CI_COMMIT_MESSAGE contains "[DEBIAN]"'

  - &ui-only
    path:
      include: [".woodpecker/ci-build.yml", "ui/**"]

  - &java-only
    path:
      include: [".woodpecker/ci-build.yml", "io.openems*/**", "**/*gradle*"]

when:
  event:
    - push

clone:
  git:
    when: &every-build
      - *main-build
      - *message-debian
      - path:
          include: [".woodpecker/ci-build.yml", "ui/**", "io.openems*/**", "**/*gradle*"]
    image: woodpeckerci/plugin-git

steps:
  restore-cache:
    when: *every-build
    image: appleboy/drone-sftp-cache
    settings:
      restore: true
      <<: *sftp-settings

  prepare-environment:
    when: *every-build
    image: bash:openems
    commands:
      - export CACHE=$CI_WORKSPACE/cache
      - mkdir -p $CI_WORKSPACE/cache build/target
      - source tools/common.sh
      - common_initialize_environment
      - common_build_snapshot_version
      - common_save_environment $CI_WORKSPACE/.openems-env
      - |
        echo "
        # Java
        export GRADLE_USER_HOME=$CACHE/gradle
        export MAVEN_OPTS=-Dmaven.repo.local=$CACHE/maven
        # Ui
        export npm_config_cache=$CACHE/npm
        export NG_CLI_CACHE_PATH=$CACHE/angular-cli
        export NODE_MODULES_CACHE=$CACHE/node_modules
        export CHROME_BIN=/usr/bin/google-chrome-stable
        " > $CI_WORKSPACE/.woodpecker-env        
      - common_update_version_in_code
    depends_on: [restore-cache]

  build-ui:
    when:
      - *main-build
      - *message-debian
      - *ui-only
    image: openems-build:21.20
    commands:
      - export OEM=$(case ${CI_COMMIT_BRANCH^^} in *HECKERT*) echo "heckert";; *) echo "fenecon";; esac)
      - source $CI_WORKSPACE/.woodpecker-env
      - source $CI_WORKSPACE/.openems-env
      ## start ##
      - echo "Build for $OEM"
      - cd ui
      - npm ci --prefer-offline --cache $npm_config_cache --force
      - sed --in-place s#/m/#/${CI_COMMIT_BRANCH}/#g angular.json src/themes/fenecon/root/site.webmanifest
      - node_modules/.bin/ng config cli.cache.path "$NG_CLI_CACHE_PATH"
      - node_modules/.bin/ng lint
      - node_modules/.bin/ng build --base-href /${CI_COMMIT_BRANCH}/ -c "$OEM,$OEM-backend-prod,prod"
      - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    depends_on: [prepare-environment]

  build-java:
    when:
      - *main-build
      - *message-debian
      - *java-only
    image: openems-build:21.20
    commands:
      - source $CI_WORKSPACE/.woodpecker-env
      - source $CI_WORKSPACE/.openems-env
      ## start ##
      - source tools/common.sh
      - common_initialize_environment
      - echo "Build Version $VERSION"
      - |
        ./gradlew checkstyleAll --parallel --max-workers=4 && \
        common_build_edge --no-build-cache --parallel --max-workers=2;        
    depends_on: [prepare-environment]

  build-debian-package:
    when:
      - *main-build
      - *message-debian
    image: openems-build:21.20
    commands:
      - source $CI_WORKSPACE/.woodpecker-env
      - source $CI_WORKSPACE/.openems-env
      ## start ##
      - mkdir -p tools/debian/usr/lib/openems/
      - cp build/openems-edge.jar tools/debian/usr/lib/openems/openems.jar
      - bash -x tools/build-debian-package.sh build/target/
    depends_on: [build-ui, build-java]

  refresh-dev-ui:
    when:
      - *main-build
      - *ui-only
    image: drillster/drone-rsync:latest
    settings:
      <<: *rsync-settings
      source: ui/target/
      recursive: true
      delete: true
      target: /opt/gitea/develop/fems-ui/html/${CI_COMMIT_BRANCH}
      script: /opt/gitea/develop/fems-ui/refresh-location.sh ${CI_COMMIT_BRANCH}
    depends_on: [build-ui]

  refresh-dev-deb:
    when:
      - *main-build
      - *message-debian
    image: drillster/drone-rsync:latest
    settings:
      <<: *rsync-settings
      source: build/target/
      target: /opt/gitea/develop/fems-artifacts/html/${CI_COMMIT_BRANCH}
    depends_on: [build-debian-package]

  rebuild-cache:
    when:
      - *main-build
    image: appleboy/drone-sftp-cache:latest
    settings:
      rebuild: true
      <<: *sftp-settings
    depends_on: [build-ui, build-java, build-debian-package]