name: Build OpenEMS Edge & Backend and docs
on: [push]
jobs:
  build-edge-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: |
        ./gradlew build
        ./gradlew resolve.BackendApp
        git diff --exit-code io.openems.backend.application/BackendApp.bndrun
        ./gradlew resolve.EdgeApp
        git diff --exit-code io.openems.edge.application/EdgeApp.bndrun
        ./gradlew buildAggregatedJavadocs --continue
        ./gradlew buildAntoraDocs --continue
